# Generated by Django 4.2.7 on 2025-06-14 16:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "starting_bid",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Puja inicial",
                    ),
                ),
                (
                    "reserve_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Precio mínimo para vender",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Precio de reserva",
                    ),
                ),
                (
                    "current_bid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Puja actual",
                    ),
                ),
                (
                    "bid_increment",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Incremento de puja",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Fecha de inicio")),
                ("end_time", models.DateTimeField(verbose_name="Fecha de fin")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "total_bids",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de pujas"
                    ),
                ),
                (
                    "watchers_count",
                    models.PositiveIntegerField(default=0, verbose_name="Seguidores"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auctions_as_seller",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vendedor",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auctions",
                        to="vehicles.vehicle",
                        verbose_name="Vehículo",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auctions_won",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ganador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subasta",
                "verbose_name_plural": "Subastas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("placed", "Placed"),
                            ("winning", "Winning"),
                            ("outbid", "Outbid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="placed",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "is_auto_bid",
                    models.BooleanField(
                        default=False, verbose_name="Es puja automática"
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Para pujas automáticas",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Cantidad máxima",
                    ),
                ),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="auctions.auction",
                        verbose_name="Subasta",
                    ),
                ),
                (
                    "bidder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pujador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Puja",
                "verbose_name_plural": "Pujas",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["auction", "amount"],
                        name="auctions_bi_auction_bac253_idx",
                    ),
                    models.Index(
                        fields=["bidder", "timestamp"],
                        name="auctions_bi_bidder__4aa89f_idx",
                    ),
                    models.Index(
                        fields=["status"], name="auctions_bi_status_838e2b_idx"
                    ),
                ],
                "unique_together": {("auction", "bidder", "timestamp")},
            },
        ),
        migrations.CreateModel(
            name="AuctionWatcher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notify_on_bid",
                    models.BooleanField(
                        default=True, verbose_name="Notificar en nueva puja"
                    ),
                ),
                (
                    "notify_on_ending",
                    models.BooleanField(
                        default=True, verbose_name="Notificar al finalizar"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchers",
                        to="auctions.auction",
                        verbose_name="Subasta",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_auctions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguidor de subasta",
                "verbose_name_plural": "Seguidores de subasta",
                "indexes": [
                    models.Index(
                        fields=["auction", "user"],
                        name="auctions_au_auction_4d7d1f_idx",
                    )
                ],
                "unique_together": {("auction", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(
                fields=["status", "start_time"], name="auctions_au_status_d4eee5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(
                fields=["seller", "status"], name="auctions_au_seller__3f4797_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(
                fields=["end_time"], name="auctions_au_end_tim_969279_idx"
            ),
        ),
    ]
